### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xjamundx**
Got the link working for the second example!

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Copy/paste fail

**Comment by loganfsmyth** [comment]
Thanks!

**Comment by xjamundx** [comment]
Yeah looked like a great talk!

**Comment by loganfsmyth** [comment]
Thanks, I tried to go to yours but the line into that building was too terrible :(

**Comment by xjamundx** [comment]
Ahh thanks, people were asking me afterwards for how-to get started with
babel advice. your talk sounds like the perfect sequel !

**Pull request merged**
